import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";
import AppShell from "@/components/AppShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata = {
  title: "Emmanuel Dabandan | Virtual Assistant",
  description: "Generated by create next app",
  icons: {
    icon: "../public/assets/MG-modified.jpg"
  }
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.variable}`}>
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
